name: Update OS Versions

on:
  workflow_dispatch: 
  schedule:
    - cron: '0 0 * * *' 
    
  push:
    branches:
      - v3.2.4
jobs:
  download-and-save:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install requests
      - name: Run Python script to update os versions
        run: python __os_config.py
                    
      - name: Commit and Push os_versions.json
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "actions-user"
          git add files/os_versions.json
          git diff --staged --exit-code || (git commit -m "Update os versions" && git push)
