name: Update User Agents

on:
  workflow_dispatch: 
  push:
    branches:
      - v3.2.4
  schedule:
    - cron: '30 0 * * *'  # Run daily at midnight

jobs:
  update-user-agents:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run script
        run: python __user_agents_config.py

      - name: Commit updated User Agents file
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "actions-user"
          git add files/user_agents.json
          git commit -m "Update user agents with new versions" || echo "No changes to commit"
          git push
